import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.animation import FuncAnimation
import sys

# 1. Load the CSV generated by the Digital Twin
file_name = "telemetry_log.csv"
try:
    df = pd.read_csv(file_name)
    print(f"Successfully loaded {len(df)} frames of telemetry from {file_name}")
except FileNotFoundError:
    print(f"Error: Could not find '{file_name}'.")
    print("Make sure you hit 'Download CSV' in the web interface and put the file in this folder.")
    sys.exit()

# 2. Setup the 3D Plotting Canvas
fig = plt.figure(figsize=(10, 8))
ax = fig.add_subplot(111, projection='3d')

# Styling to look professional
ax.set_title("Team Vyasa - Digital Twin Telemetry Replay", pad=20, fontsize=14, fontweight='bold')
ax.set_xlabel("X (meters)")
ax.set_ylabel("Z (meters) - Depth") 
ax.set_zlabel("Y (meters) - Elevation")
ax.grid(True, linestyle='--', alpha=0.6)

# Create scatter points for the trucks
scat1 = ax.scatter([], [], [], c='#0044ff', label='Truck 1', s=80, marker='s')
scat2 = ax.scatter([], [], [], c='#ff3300', label='Truck 2', s=80, marker='^')

# Create lines to track their path history
line1, = ax.plot([], [], [], c='#0044ff', alpha=0.4, linewidth=2)
line2, = ax.plot([], [], [], c='#ff3300', alpha=0.4, linewidth=2)

ax.legend()

# 3. Dynamic Axes Scaling
# We calculate the boundaries based on where the trucks drove so the map scales perfectly
margin = 20
ax.set_xlim(df[['T1_X', 'T2_X']].min().min() - margin, df[['T1_X', 'T2_X']].max().max() + margin)
ax.set_ylim(df[['T1_Z', 'T2_Z']].min().min() - margin, df[['T1_Z', 'T2_Z']].max().max() + margin)
ax.set_zlim(df[['T1_Y', 'T2_Y']].min().min() - margin, df[['T1_Y', 'T2_Y']].max().max() + margin)

# 4. The Animation Loop
def update(frame):
    # Slice the dataframe up to the current frame to draw the trailing lines
    curr_df = df.iloc[:frame+1]
    row = df.iloc[frame]
    
    # Matplotlib 3D takes (X, Y, Z). Our data is (X, Depth=Z, Elevation=Y)
    scat1._offsets3d = ([row['T1_X']], [row['T1_Z']], [row['T1_Y']])
    scat2._offsets3d = ([row['T2_X']], [row['T2_Z']], [row['T2_Y']])
    
    line1.set_data_3d(curr_df['T1_X'], curr_df['T1_Z'], curr_df['T1_Y'])
    line2.set_data_3d(curr_df['T2_X'], curr_df['T2_Z'], curr_df['T2_Y'])
    
    return scat1, scat2, line1, line2

# Run the animation at roughly 10Hz (100ms interval) to match the recording speed
print("Starting Replay...")
ani = FuncAnimation(fig, update, frames=len(df), interval=100, blit=False)

plt.show()